"use client";

import JSZip from "jszip";
import Link from "next/link";
import { Archive, Camera, FileCode2, FilePlus2, FileUp, FolderGit2, LoaderCircle, Mic, Search, Send, Sparkles, Upload } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import AppShell from "@/components/AppShell";

type FileItem={path:string;content:string};
type Message={role:"user"|"assistant";text:string};
type ToolResult={type:string;path?:string;content?:string;result?:unknown;error?:string};

export default function AgentWorkspace(){
  const [files,setFiles]=useState<FileItem[]>([{path:"README.md",content:"# ELIAS project\n\nImport a project ZIP or add files, then tell ELIAS what to build."}]);
  const [active,setActive]=useState("README.md"); const [query,setQuery]=useState(""); const [task,setTask]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [busy,setBusy]=useState(false); const [status,setStatus]=useState("ready");
  const zipInput=useRef<HTMLInputElement>(null); const filesInput=useRef<HTMLInputElement>(null); const cameraInput=useRef<HTMLInputElement>(null); const workspaceRef=useRef(files); workspaceRef.current=files;
  const current=files.find(f=>f.path===active)||files[0]; const visible=useMemo(()=>files.filter(f=>f.path.toLowerCase().includes(query.toLowerCase())),[files,query]);

  async function addZip(file:File){const zip=await JSZip.loadAsync(file);const next:FileItem[]=[];for(const [path,obj] of Object.entries(zip.files)){if(obj.dir)continue;const ext=path.toLowerCase().split(".").pop();if(["png","jpg","jpeg","gif","webp","mp4","mov","pdf","woff","woff2","ttf","ico"].includes(ext||""))continue;next.push({path,content:await obj.async("string")});}if(next.length){setFiles(next);setActive(next[0].path);setMessages(m=>[...m,{role:"assistant",text:`imported ${next.length} text/code files from the ZIP.`}]);}}
  async function addLoose(list:FileList|null){if(!list)return;const add:FileItem[]=[];for(const f of Array.from(list)){if(f.size>15_000_000)continue;try{add.push({path:f.webkitRelativePath||f.name,content:await f.text()})}catch{}}if(add.length){setFiles(old=>merge(old,add));setActive(add[0].path);setMessages(m=>[...m,{role:"assistant",text:`added ${add.length} files.`}]);}}
  async function addImage(file:File){setMessages(m=>[...m,{role:"assistant",text:`received ${file.name}. image understanding can be routed through a vision-capable provider when enabled.`}]);}

  function applyActions(actions:any[]){setFiles(old=>{let next=[...old];for(const a of actions){if(a.type==="write_file"&&a.path){const item={path:a.path,content:String(a.content??"")};const i=next.findIndex(f=>f.path===a.path);if(i>=0)next[i]=item;else next.push(item);setActive(a.path)}else if(a.type==="append_file"&&a.path){const i=next.findIndex(f=>f.path===a.path);if(i>=0)next[i]={...next[i],content:next[i].content+String(a.content??"")}}else if(a.type==="delete_file"&&a.path){next=next.filter(f=>f.path!==a.path);if(active===a.path)setActive(next[0]?.path||"")}else if(a.type==="rename_file"&&a.path&&a.to){next=next.map(f=>f.path===a.path?{...f,path:a.to}:f);if(active===a.path)setActive(a.to)}}return next});}

  async function run(){const prompt=task.trim();if(!prompt||busy)return;setTask("");setBusy(true);setStatus("starting");setMessages(m=>[...m,{role:"user",text:prompt}]);let conversation:{role:string;content:string}[]=[{role:"user",content:prompt}];let tools:ToolResult[]=[];
    try{for(let step=1;step<=12;step++){setStatus(`working · ${step}/12`);const snapshot=workspaceRef.current;const r=await fetch("/api/agent/step",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({task:prompt,taskType:inferTask(prompt),files:snapshot.map(f=>({path:f.path,content:f.content})),messages:conversation,toolResults:tools})});const d=await r.json();if(!r.ok)throw new Error(d.error||"agent failed");if(d.message){setMessages(m=>[...m,{role:"assistant",text:d.message}]);conversation=[...conversation,{role:"assistant",content:d.message}]}
        const results:ToolResult[]=[];for(const req of d.requests||[]){if(req.type==="read_file"&&req.path){const f=workspaceRef.current.find(x=>x.path===req.path);results.push(f?{type:"read_file",path:req.path,content:f.content}:{type:"read_file",path:req.path,error:"file not found"})}else if(req.type==="search_web"&&req.query){const x=await fetch("/api/web/search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:req.query})});results.push({type:"search_web",query:req.query,result:await x.json()} as any)}else if(req.type==="get_url"&&req.url){const x=await fetch("/api/web/open",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url:req.url})});results.push({type:"get_url",url:req.url,result:await x.json()} as any)}}
        if(d.actions?.length)applyActions(d.actions);tools=[...tools,...results];if(results.length)conversation=[...conversation,{role:"tool",content:JSON.stringify(results).slice(0,100000)}];if(d.done){setStatus("completed");break}}
    }catch(e){setStatus("error");setMessages(m=>[...m,{role:"assistant",text:e instanceof Error?e.message:"ELIAS failed"}])}finally{setBusy(false)}}

  async function downloadZip(){const z=new JSZip();workspaceRef.current.forEach(f=>z.file(f.path,f.content));const blob=await z.generateAsync({type:"blob"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download="elias-project.zip";a.click();URL.revokeObjectURL(u)}

  return <AppShell title="Agent"><main className="screen agent-workspace">
    <div className="agent-head"><div><p className="eyebrow">ELIAS / autonomous workspace</p><h1>build it. change it. ship it.</h1></div><span className={`agent-state ${status}`}>{busy&&<LoaderCircle size={13} className="spin"/>}<Sparkles size={13}/>{status}</span></div>
    <div className="workspace-toolbar"><button onClick={()=>zipInput.current?.click()}><Archive size={14}/> import ZIP</button><button onClick={()=>filesInput.current?.click()}><Upload size={14}/> add files</button><button onClick={()=>cameraInput.current?.click()}><Camera size={14}/> photo</button><button onClick={downloadZip}><Archive size={14}/> export ZIP</button><Link href="/studio"><Mic size={14}/> voice</Link><input ref={zipInput} hidden type="file" accept=".zip" onChange={e=>e.target.files?.[0]&&addZip(e.target.files[0])}/><input ref={filesInput} hidden type="file" multiple onChange={e=>addLoose(e.target.files)}/><input ref={cameraInput} hidden type="file" accept="image/*" capture="environment" onChange={e=>e.target.files?.[0]&&addImage(e.target.files[0])}/></div>
    <div className="workspace">
      <aside className="workspace-files"><div className="workspace-pane-title"><span>files · {files.length}</span><button onClick={()=>filesInput.current?.click()}><FilePlus2 size={14}/></button></div><div className="file-search"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="find file"/></div><div className="file-tree">{visible.map(f=><button key={f.path} className={f.path===active?"selected":""} onClick={()=>setActive(f.path)}><FileCode2 size={13}/><span>{f.path}</span></button>)}</div></aside>
      <section className="workspace-editor"><div className="editor-top"><span>{current?.path}</span><span>{current?.content.length||0} chars</span></div><textarea spellCheck={false} value={current?.content||""} onChange={e=>current&&setFiles(old=>old.map(f=>f.path===current.path?{...f,content:e.target.value}:f))}/></section>
      <aside className="workspace-agent"><div className="workspace-pane-title"><span><Sparkles size={14}/> ELIAS</span><span className="tiny-live">multi-model</span></div><div className="agent-log">{messages.length?messages.map((m,i)=><div className={`log ${m.role}`} key={i}><small>{m.role==="assistant"?"ELIAS":"YOU"}</small><p>{m.text}</p></div>):<div className="agent-empty"><Sparkles size={24}/><b>give ELIAS a real task</b><small>import your codebase, then ask it to inspect, research, edit and iterate.</small></div>}</div><div className="agent-input"><textarea rows={3} value={task} onChange={e=>setTask(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void run()}}} placeholder="e.g. refactor the auth flow across the whole project..."/><div><button title="upload photo" onClick={()=>cameraInput.current?.click()}><Camera size={15}/></button><button title="voice" onClick={()=>window.location.href="/studio"}><Mic size={15}/></button><button className="agent-send" disabled={busy} onClick={run}>{busy?<LoaderCircle size={16} className="spin"/>:<Send size={16}/>}</button></div></div></aside>
    </div>
  </main></AppShell>
}
function merge(old:FileItem[],add:FileItem[]){const m=new Map(old.map(x=>[x.path,x]));add.forEach(x=>m.set(x.path,x));return [...m.values()]}
function inferTask(v:string){const s=v.toLowerCase();if(/research|latest|today|current|news|search the web|source/.test(s))return"research";if(/study|exam|notes|flashcard|pdf|chapter|document/.test(s))return"study";if(/build|code|bug|debug|tsx|jsx|html|css|typescript|javascript|repository|github|refactor|implement/.test(s))return"code";return"general"}
