"use client";

import { Archive, Download, FileCode2, FileText, Image as ImageIcon } from "lucide-react";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";
import ScreenHeader from "@/components/ScreenHeader";
import { getArtifacts, type ArtifactRecord } from "@/lib/persistence";

export default function FilesScreen() {
  const [artifacts, setArtifacts] = useState<ArtifactRecord[]>([]);

  useEffect(() => {
    void getArtifacts().then(setArtifacts).catch(() => setArtifacts([]));
  }, []);

  function download(artifact: ArtifactRecord) {
    if (!artifact.blob) return;
    const url = URL.createObjectURL(artifact.blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = artifact.name;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return (
    <AppShell title="Files">
      <main className="screen">
        <ScreenHeader title="Artifacts / files" />

        <section className="panel file-library-head">
          <div>
            <p className="eyebrow">persistent artifacts</p>
            <h2>Your generated files</h2>
            <small>
              ZIPs and outputs generated by ELIAS stay available in this browser.
            </small>
          </div>
        </section>

        <div className="file-list">
          {artifacts.map((artifact) => (
            <div className="file-row" key={artifact.id}>
              <span className="file-icon">
                {artifact.name.endsWith(".zip") ? (
                  <Archive size={17} />
                ) : artifact.name.match(/\.(png|jpg|jpeg|webp)$/i) ? (
                  <ImageIcon size={17} />
                ) : artifact.name.match(/\.(tsx|ts|jsx|js|css|html)$/i) ? (
                  <FileCode2 size={17} />
                ) : (
                  <FileText size={17} />
                )}
              </span>

              <span>
                <strong>{artifact.name}</strong>
                <small>{new Date(artifact.createdAt).toLocaleString()}</small>
              </span>

              {artifact.blob ? (
                <button
                  className="icon-btn"
                  title="Download"
                  onClick={() => download(artifact)}
                >
                  <Download size={16} />
                </button>
              ) : null}
            </div>
          ))}

          {!artifacts.length && (
            <div className="empty-projects">
              <Archive size={22} />
              <b>No artifacts yet</b>
              <small>
                Export a project ZIP from an ELIAS coding workspace and it will appear here.
              </small>
            </div>
          )}
        </div>
      </main>
    </AppShell>
  );
}
