"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, Github, Link2, LoaderCircle, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";

type Repo = { id: number; fullName: string; name: string; private: boolean; description: string; url: string; defaultBranch: string; language: string };

export default function GitHubConnectorScreen() {
  const [connected, setConnected] = useState(false);
  const [repos, setRepos] = useState<Repo[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState("");
  async function loadRepos() { setLoading(true); try { const response = await fetch("/api/github/repos", { cache: "no-store" }); const data = await response.json(); setConnected(Boolean(data.connected)); setRepos(data.repositories || []); setMessage(data.message || ""); } catch { setMessage("Could not load GitHub repositories."); } finally { setLoading(false); } }
  useEffect(() => { void loadRepos(); }, []);
  const filtered = repos.filter((repo) => `${repo.fullName} ${repo.description}`.toLowerCase().includes(query.toLowerCase()));
  return <AppShell title="GitHub"><main className="screen connector-detail-screen"><div className="mobile-screen-heading"><Link href="/connectors" aria-label="Back to connectors"><ArrowLeft size={19} /></Link><h1>GitHub</h1><span className="detail-menu">•••</span></div><section className="connector-hero-card"><span className="connector-hero-icon"><Github size={31} /></span><h2>GitHub</h2><p>Access repositories, review code changes, track issues, and connect project context to Elias.</p></section><section className="detail-list"><div><span>Connector type</span><strong>OAuth App</strong></div><div><span>Authorization</span><strong>{connected ? "This Elias account" : "Not connected"}</strong></div><div><span>Repositories</span><strong>{connected ? repos.length : "—"}</strong></div></section><section className="connector-auth-card">{connected ? <div className="connected-heading"><CheckCircle2 size={18} /><span><strong>GitHub connected</strong><small>This Elias account can use its authorized repositories.</small></span></div> : <><div className="auth-heading"><Link2 size={18} /><span><strong>Authorize GitHub</strong><small>GitHub will open its confirmation screen. Choose the repositories Elias may access.</small></span></div><a className="primary wide connector-cta" href="/api/connect/github"><ShieldCheck size={15} /> Authorize GitHub account</a></>}{message ? <p className="connector-help">{message}</p> : null}</section>{connected ? <section className="repos-panel"><div className="panel-head"><span><Github size={16} /><strong>Available repositories</strong></span><b>{repos.length}</b></div><div className="searchbox repo-search"><Search size={14} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search repositories" /></div>{loading ? <div className="repo-loading"><LoaderCircle className="spin" size={17} /> Loading repositories…</div> : filtered.length ? <div className="repo-list">{filtered.map((repo) => <a className="repo-row" href={repo.url} target="_blank" rel="noreferrer" key={repo.id}><span className="repo-avatar"><Github size={14} /></span><span><strong>{repo.fullName}</strong><small>{repo.description}</small><em>{repo.private ? "Private" : "Public"} · {repo.language} · {repo.defaultBranch}</em></span><ExternalLink size={14} /></a>)}</div> : <div className="repo-empty">No repositories match this search.</div>}</section> : null}<div className="connector-links"><a href="https://github.com/settings/developers" target="_blank" rel="noreferrer">GitHub Developer Settings <ExternalLink size={13} /></a><a href="https://docs.github.com/en/rest/repos/repos#list-repositories-for-the-authenticated-user" target="_blank" rel="noreferrer">GitHub repository API <ExternalLink size={13} /></a></div></main></AppShell>;
}
