"use client";

import Link from "next/link";
import { ArrowLeft, Brain, Check, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import AppShell from "@/components/AppShell";
import { deleteMemory, getMemories, makeId, saveMemory, type MemoryRecord } from "@/lib/persistence";

export default function MemoryScreen() {
  const [memories, setMemories] = useState<MemoryRecord[]>([]);
  const [kind, setKind] = useState<MemoryRecord["kind"]>("preference");
  const [title, setTitle] = useState("");
  const [value, setValue] = useState("");
  const [confidence, setConfidence] = useState<MemoryRecord["confidence"]>("high");
  const [showForm, setShowForm] = useState(false);
  useEffect(() => { void getMemories().then(setMemories).catch(() => undefined); }, []);
  async function add(event: FormEvent) { event.preventDefault(); if (!title.trim() || !value.trim()) return; const timestamp = Date.now(); const record: MemoryRecord = { id: makeId("memory"), kind, title: title.trim(), value: value.trim(), confidence, source: "user-approved", createdAt: timestamp, updatedAt: timestamp }; await saveMemory(record); setMemories((current) => [record, ...current]); setTitle(""); setValue(""); setShowForm(false); }
  async function remove(id: string) { await deleteMemory(id); setMemories((current) => current.filter((item) => item.id !== id)); }
  return <AppShell title="Memory"><main className="screen memory-screen"><div className="mobile-screen-heading"><Link href="/profile" aria-label="Back to profile"><ArrowLeft size={19} /></Link><h1>memory</h1><span className="improvement-mark"><Brain size={16} /></span></div><section className="memory-hero"><div><p className="eyebrow">ELIAS / user-controlled memory</p><h2>Remember what you approve.</h2><p>Preferences, project conventions, and useful observations stay separate from temporary task context. Nothing becomes permanent without your approval.</p></div><ShieldCheck size={34} /></section><section className="panel memory-toolbar"><div className="memory-stat-copy"><strong>{memories.length} active memory item{memories.length === 1 ? "" : "s"}</strong><small>Stored in your user-partitioned Elias workspace.</small></div><button className="primary" onClick={() => setShowForm((value) => !value)}><Plus size={15} /> add memory</button></section>{showForm ? <form className="panel memory-form" onSubmit={add}><div className="form-grid"><label>Type<select value={kind} onChange={(event) => setKind(event.target.value as MemoryRecord["kind"])}><option value="preference">User preference</option><option value="project">Project convention</option><option value="task">Task context</option><option value="observation">Observation</option></select></label><label>Title<input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Preferred response style" /></label></div><label>Memory value<textarea required rows={4} value={value} onChange={(event) => setValue(event.target.value)} placeholder="Use concise technical explanations with a short implementation summary." /></label><label>Confidence<select value={confidence} onChange={(event) => setConfidence(event.target.value as MemoryRecord["confidence"])}><option value="high">High — explicitly confirmed</option><option value="medium">Medium — likely useful</option><option value="low">Low — temporary observation</option></select></label><button className="primary" type="submit"><Check size={15} /> save approved memory</button></form> : null}<section className="memory-list">{memories.length ? memories.map((memory) => <article className="panel memory-row" key={memory.id}><div className="memory-row-main"><span className={`memory-kind ${memory.kind}`}>{memory.kind}</span><strong>{memory.title}</strong><p>{memory.value}</p><small>Confidence: {memory.confidence} · Source: {memory.source || "Elias"}</small></div><button className="icon-btn" onClick={() => void remove(memory.id)} aria-label={`Delete ${memory.title}`}><Trash2 size={15} /></button></article>) : <section className="panel memory-empty"><Brain size={25} /><div className="memory-empty-copy"><strong>No approved memories yet</strong><small>Add a preference or project convention. Elias will not silently promote uncertain observations into permanent memory.</small></div></section>}</section></main></AppShell>;
}
