"use client";

import Link from "next/link";
import { ArrowLeft, Bell, ChevronRight, CircleHelp, Clock3, Database, Globe2, KeyRound, Lightbulb, LogOut, Moon, Puzzle, ShieldCheck, Sparkles, UserCircle, WalletCards } from "lucide-react";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";

type User = { name?: string; login?: string; email?: string; avatarUrl?: string; githubConnected?: boolean; vercelConnected?: boolean };
function Row({ icon, label, detail, href }: { icon: React.ReactNode; label: string; detail?: string; href?: string }) { const content = <><span className="profile-row-icon">{icon}</span><span className="profile-row-copy"><strong>{label}</strong>{detail ? <small>{detail}</small> : null}</span><ChevronRight size={17} /></>; return href ? <Link className="profile-row" href={href}>{content}</Link> : <button className="profile-row" type="button">{content}</button>; }

export default function ProfileScreen() {
  const [user, setUser] = useState<User>({});
  useEffect(() => { void fetch("/api/auth/me", { cache: "no-store" }).then((r) => r.json()).then((d) => setUser(d.user || {})).catch(() => undefined); }, []);
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }
  const initial = (user.name || user.login || "C").slice(0, 1).toUpperCase();
  return <AppShell title="Profile"><main className="screen profile-screen"><div className="profile-titlebar"><Link href="/chat" aria-label="Back to chat"><ArrowLeft size={19} /></Link><span className="profile-wordmark">elias</span><Bell size={18} /></div><section className="account-card"><span className="account-avatar">{user.avatarUrl ? <img src={user.avatarUrl} alt="" /> : initial}</span><span><strong>{user.name || user.login || "Your Elias account"}</strong><small>{user.login ? `@${user.login}` : "Personal workspace"}</small></span></section><section className="plan-card"><div><span className="plan-label">Personal plan</span><strong>Free</strong></div><button className="upgrade-button" type="button">Upgrade</button><Row icon={<Sparkles size={17} />} label="Credits" detail="Available for your workspace" /></section><section className="profile-group"><Row icon={<Clock3 size={18} />} label="Scheduled tasks" href="/tasks" /><Row icon={<Lightbulb size={18} />} label="Knowledge" href="/files" /><Row icon={<Database size={18} />} label="Data controls" /><Row icon={<Globe2 size={18} />} label="Cloud Browser" /><Row icon={<Puzzle size={18} />} label="Skills" /><Row icon={<Sparkles size={18} />} label="Improvement Center" detail="Feedback, evaluations, proposals" href="/improvements" /><Row icon={<Puzzle size={18} />} label="Connectors" detail={user.vercelConnected || user.githubConnected ? "Connected services" : "No services connected"} href="/connectors" /><Row icon={<WalletCards size={18} />} label="Integrations" /></section><section className="profile-group"><Row icon={<UserCircle size={18} />} label="Account" detail={user.email || user.login} /><Row icon={<Globe2 size={18} />} label="Language" detail="English" /><Row icon={<Moon size={18} />} label="Appearance" detail="Follow system" /><Row icon={<ShieldCheck size={18} />} label="Privacy and security" href="/privacy" /></section><section className="profile-group profile-actions"><Row icon={<CircleHelp size={18} />} label="Help and feedback" /><button className="profile-row danger-row" type="button" onClick={() => void logout()}><span className="profile-row-icon"><LogOut size={18} /></span><span className="profile-row-copy"><strong>Sign out</strong><small>End this Elias session</small></span></button></section></main></AppShell>;
}
