"use client";

import Link from "next/link";
import { ArrowLeft, ArrowUpRight, GitCommitHorizontal, Github, GitPullRequest, LoaderCircle, LockKeyhole, MessageSquare, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";

type Workspace = { repository: { fullName: string; name: string; description: string; private: boolean; url: string; defaultBranch: string; language: string; stars: number; openIssues: number }; commits: Array<{ sha: string; url: string; message: string; author: string; date?: string }> };

export default function RepositoryWorkspaceScreen({ owner, repo }: { owner: string; repo: string }) {
  const [data, setData] = useState<Workspace | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void fetch(`/api/github/repositories/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`, { cache: "no-store" }).then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Could not load repository."); setData(payload); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Could not load repository.")); }, [owner, repo]);
  return <AppShell title={repo}><main className="screen repository-workspace-screen"><div className="mobile-screen-heading"><Link href="/connectors/github" aria-label="Back to GitHub"><ArrowLeft size={19} /></Link><h1>{repo}</h1><a className="icon-btn" href={`https://github.com/${owner}/${repo}`} target="_blank" rel="noreferrer" aria-label="Open on GitHub"><ArrowUpRight size={17} /></a></div>{error ? <section className="panel repo-workspace-error"><Github size={22} /><strong>{error}</strong><Link className="secondary" href="/connectors/github">Back to GitHub repositories</Link></section> : !data ? <div className="repo-loading"><LoaderCircle className="spin" size={18} /> Loading Elias workspace…</div> : <><section className="repo-workspace-hero"><span className="repo-workspace-icon"><Github size={27} /></span><div><p className="eyebrow">ELIAS / repository workspace</p><h2>{data.repository.fullName}</h2><p>{data.repository.description}</p></div><span className="repo-visibility">{data.repository.private ? <LockKeyhole size={12} /> : null}{data.repository.private ? "Private" : "Public"}</span></section><div className="repo-metrics"><div><b>{data.repository.defaultBranch}</b><span>default branch</span></div><div><b>{data.repository.openIssues}</b><span>open issues</span></div><div><b>{data.repository.stars}</b><span>stars</span></div></div><section className="workspace-actions"><button className="primary"><Sparkles size={15} /> Ask Elias about this repo</button><button className="secondary"><GitPullRequest size={15} /> Pull requests</button><button className="secondary"><MessageSquare size={15} /> Issues</button></section><section className="panel"><div className="panel-head"><span><GitCommitHorizontal size={16} /><strong>Recent repository activity</strong></span><span>{data.repository.language}</span></div><div className="repo-commit-list">{data.commits.map((commit) => <a href={commit.url} target="_blank" rel="noreferrer" className="repo-commit-row" key={commit.sha}><GitCommitHorizontal size={14} /><span><strong>{commit.message}</strong><small>{commit.author}{commit.date ? ` · ${new Date(commit.date).toLocaleDateString()}` : ""}</small></span><ArrowUpRight size={14} /></a>)}</div></section><div className="workspace-footnote">You are working inside Elias. Open GitHub only when you need the provider’s native interface.</div></>}</main></AppShell>;
}
