"use client";

import Link from "next/link";
import { ArrowLeft, Brain, FileText, FolderKanban, Lightbulb, MessageSquare, Search as SearchIcon, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import AppShell from "@/components/AppShell";
import { getArtifacts, getConversations, getImprovements, getMemories, getProjects, type ArtifactRecord, type ConversationRecord, type ImprovementRecord, type MemoryRecord, type ProjectRecord } from "@/lib/persistence";

type SearchResult = { id: string; type: string; title: string; detail: string; href: string; icon: React.ReactNode };

export default function SearchScreen() {
  const [query, setQuery] = useState("");
  const [data, setData] = useState<{ conversations: ConversationRecord[]; artifacts: ArtifactRecord[]; projects: ProjectRecord[]; improvements: ImprovementRecord[]; memories: MemoryRecord[] }>({ conversations: [], artifacts: [], projects: [], improvements: [], memories: [] });
  useEffect(() => { void Promise.all([getConversations(), getArtifacts(), getProjects(), getImprovements(), getMemories()]).then(([conversations, artifacts, projects, improvements, memories]) => setData({ conversations, artifacts, projects, improvements, memories })).catch(() => undefined); }, []);
  const results = useMemo<SearchResult[]>(() => { const term = query.trim().toLowerCase(); if (!term) return []; const matches = (value: string) => value.toLowerCase().includes(term); const output: SearchResult[] = []; data.conversations.forEach((item) => { if (matches(`${item.title} ${item.messages.map((message) => message.content).join(" ")}`)) output.push({ id: item.id, type: "conversation", title: item.title, detail: `${item.messages.length} messages`, href: `/chat?id=${encodeURIComponent(item.id)}`, icon: <MessageSquare size={16} /> }); }); data.artifacts.forEach((item) => { if (matches(`${item.name} ${item.summary || ""} ${item.text || ""}`)) output.push({ id: item.id, type: "document", title: item.name, detail: `${item.pageCount || 1} pages · ${item.chunks?.length || 0} chunks`, href: "/files", icon: <FileText size={16} /> }); }); data.projects.forEach((item) => { if (matches(`${item.name} ${item.description || ""}`)) output.push({ id: item.id, type: "project", title: item.name, detail: item.description || "Project workspace", href: `/projects/${encodeURIComponent(item.id)}`, icon: <FolderKanban size={16} /> }); }); data.improvements.forEach((item) => { if (matches(`${item.title} ${item.detail}`)) output.push({ id: item.id, type: "improvement", title: item.title, detail: `${item.status} · ${item.source || "Elias"}`, href: "/improvements", icon: <Lightbulb size={16} /> }); }); data.memories.forEach((item) => { if (matches(`${item.title} ${item.value}`)) output.push({ id: item.id, type: "memory", title: item.title, detail: item.value, href: "/memory", icon: <Brain size={16} /> }); }); return output.slice(0, 50); }, [data, query]);
  return <AppShell title="Search"><main className="screen search-screen"><div className="mobile-screen-heading"><Link href="/chat" aria-label="Back to chat"><ArrowLeft size={19} /></Link><h1>universal search</h1><span className="improvement-mark"><SearchIcon size={16} /></span></div><section className="search-hero"><p className="eyebrow">ELIAS / workspace search</p><h2>Find anything you have built, asked, or approved.</h2><p>Search your user-scoped conversations, documents, projects, improvement signals, and memory from one place.</p></section><label className="universal-search-box"><SearchIcon size={17} /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Elias workspace…" /></label>{query.trim() ? <section className="search-results">{results.length ? results.map((result) => <Link className="search-result-row" href={result.href} key={`${result.type}-${result.id}`}><span className="search-result-icon">{result.icon}</span><span><b>{result.title}</b><small>{result.type} · {result.detail}</small></span><Sparkles size={13} /></Link>) : <div className="panel search-empty"><SearchIcon size={23} /><strong>No matching workspace records</strong><small>Try a project name, document title, phrase from a conversation, or an improvement signal.</small></div>}</section> : <section className="panel search-empty"><SearchIcon size={23} /><strong>Search across your Elias workspace</strong><small>Results stay scoped to the signed-in browser workspace.</small></section>}</main></AppShell>;
}
