"use client";

import Link from "next/link";
import { ArrowLeft, CheckCircle2, ChevronRight, Cloud, ExternalLink, KeyRound, LoaderCircle, LogOut, ShieldCheck, Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import AppShell from "@/components/AppShell";

type Status = { connected?: boolean; needsToken?: boolean; message?: string; account?: { username?: string; name?: string }; tools?: Array<{ name: string; description?: string }> };
const defaultTools = [{ name: "list_projects", description: "List projects visible to this Vercel account." }, { name: "get_project", description: "Inspect project settings and repository linkage." }, { name: "list_project_domains", description: "List domains attached to a project." }, { name: "get_deployment", description: "Inspect a deployment by ID or hostname." }, { name: "get_deployment_build_logs", description: "Read recent build events for a deployment." }];

export default function VercelConnectorScreen() {
  const [status, setStatus] = useState<Status>({ tools: defaultTools });
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  async function refresh() { const response = await fetch("/api/auth/me", { cache: "no-store" }); const data = await response.json(); setStatus((current) => ({ ...current, connected: Boolean(data.user?.vercelConnected), tools: defaultTools })); }
  useEffect(() => { void refresh(); }, []);
  async function connect() { if (!token.trim()) return; setBusy(true); try { const response = await fetch("/api/connect/vercel", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }); const data = await response.json(); setStatus({ ...data, tools: data.tools?.length ? data.tools : defaultTools }); if (data.connected) setToken(""); } finally { setBusy(false); } }
  async function disconnect() { setBusy(true); try { await fetch("/api/connect/vercel", { method: "DELETE" }); setStatus({ connected: false, tools: defaultTools, message: "Vercel disconnected from this Elias account." }); } finally { setBusy(false); } }
  const tools = status.tools?.length ? status.tools : defaultTools;
  return <AppShell title="Vercel"><main className="screen connector-detail-screen"><div className="mobile-screen-heading"><Link href="/connectors" aria-label="Back to connectors"><ArrowLeft size={19} /></Link><h1>Vercel</h1><span className="detail-menu">•••</span></div><section className="connector-hero-card"><span className="connector-hero-icon"><span className="vercel-glyph large">▲</span></span><h2>Vercel</h2><p>Manage projects, inspect deployments, and read build logs through Elias’s MCP bridge.</p></section><section className="detail-list"><div><span>Connector type</span><strong>MCP</strong></div><div><span>Authorization</span><strong>{status.connected ? "This Elias account" : "Not connected"}</strong></div><div><span>Provider</span><strong>Vercel</strong></div></section>{status.connected ? <section className="connector-connected-card"><div className="connected-heading"><CheckCircle2 size={18} /><span><strong>Connected</strong><small>{status.account?.username ? `@${status.account.username}` : "Vercel account verified"}</small></span><button className="text-action" onClick={() => void disconnect()} disabled={busy}><LogOut size={14} /> Disconnect</button></div></section> : <section className="connector-auth-card"><div className="auth-heading"><KeyRound size={18} /><span><strong>Connect your Vercel account</strong><small>Create a token at vercel.com/account/tokens, then paste it here. It is encrypted in your Elias session and never shown again.</small></span></div><input value={token} onChange={(event) => setToken(event.target.value)} type="password" placeholder="Paste Vercel API token" autoComplete="off" /><button className="primary wide" disabled={!token.trim() || busy} onClick={() => void connect()}>{busy ? <LoaderCircle className="spin" size={15} /> : <ShieldCheck size={15} />} {busy ? "verifying…" : "Authorize Vercel account"}</button>{status.message ? <small className="inline-status">{status.message}</small> : null}</section>}<section className="tools-panel"><div className="panel-head"><span><Wrench size={16} /><strong>Available tools</strong></span><b>{tools.length}</b></div>{tools.map((tool) => <div className="tool-row" key={tool.name}><span className="tool-icon"><Cloud size={15} /></span><span><strong>{tool.name}</strong><small>{tool.description}</small></span><ChevronRight size={15} /></div>)}</section><div className="connector-links"><a href="https://vercel.com/account/tokens" target="_blank" rel="noreferrer">Get a Vercel token <ExternalLink size={13} /></a><a href="https://vercel.com/docs/agent-resources/vercel-mcp" target="_blank" rel="noreferrer">Vercel MCP documentation <ExternalLink size={13} /></a></div></main></AppShell>;
}
