import type { SkillDefinition } from "@/lib/skills";

export const EXTENDED_SKILL_DEFINITIONS: SkillDefinition[] = [
  { id: "elias-api", name: "Elias API", description: "Build and operate API integrations, OAuth flows, task lifecycles, structured outputs, webhooks, connectors, and durable agent workflows for Elias.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["elias-api.tasks", "elias-api.projects", "elias-api.files", "elias-api.webhooks", "elias-api.connectors", "elias-api.skills", "elias-api.structured-output"], permissions: ["API integration design", "OAuth configuration", "Task and webhook management", "Connector administration with confirmation"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "typst-pdf-maker", name: "Typst PDF Maker", description: "Create polished, structured PDFs with Typst using deterministic routing, content manifests, compile preflight, verification, and visual review.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["typst.manifest.create", "typst.plan", "typst.compile", "typst.verify", "typst.render-review"], permissions: ["Document generation", "Local file creation", "PDF compilation", "PDF verification"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "video-generator", name: "Video Generator", description: "Plan and produce AI video projects with explicit requirements, global definitions, clip continuity, reference images, audio mixing, and confirmation gates.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["video.brief", "video.storyboard", "video.reference-image", "video.generate", "video.audio-mix", "video.export"], permissions: ["Media generation", "Reference image generation", "Audio mixing", "Video export"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "youtube-video-research", name: "YouTube Video Research", description: "Discover and analyze YouTube videos as first-hand evidence, extract structured quotes and data, cross-validate claims, and synthesize cited research.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["web.search", "youtube.discover", "youtube.analyze", "video.transcribe", "evidence.cite"], permissions: ["Web search", "YouTube video analysis", "Transcript extraction", "Source citation"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "tts-prompter", name: "TTS Prompter", description: "Craft expressive text-to-speech prompts by separating English director instructions from spoken text, with language, accent, pacing, emotion, and local action tags.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["tts.prompt", "tts.voice.select", "tts.generate", "audio.preview"], permissions: ["Speech generation", "Voice selection", "Audio preview"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "stock-analysis", name: "Stock Analysis", description: "Analyze stocks and companies with profile, price, chart, technical, fundamental, insider, and regulatory-filing evidence while separating analysis from personalized financial advice.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["market.profile", "market.chart", "market.insights", "market.holders", "market.sec-filings", "market.compare"], permissions: ["Market-data read", "SEC filing read", "Financial analysis", "Report generation"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "similarweb-analytics", name: "SimilarWeb Analytics", description: "Analyze website traffic, visits, engagement, rankings, marketing channels, and geographic distribution with date-bounded SimilarWeb evidence.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["similarweb.rank", "similarweb.visits", "similarweb.unique-visits", "similarweb.bounce-rate", "similarweb.traffic-sources", "similarweb.geography"], permissions: ["Website analytics read", "Traffic-data analysis", "Competitor comparison"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "music-prompter", name: "Music Prompter", description: "Craft coherent music-generation prompts using genre, tempo, key, mood, instrumentation, density, arrangement, soundscape, and production-quality controls.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["music.prompt", "music.generate", "music.continuity-plan", "audio.export"], permissions: ["Music generation", "Audio export", "Multi-clip continuity planning"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "excel-generator", name: "Excel Generator", description: "Create professional, usable Excel workbooks with clear structure, formulas, source attribution, summaries, charts, filters, validation, and appropriate formatting authority.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-21", tools: ["spreadsheet.create", "spreadsheet.formulas", "spreadsheet.chart", "spreadsheet.validate", "spreadsheet.export"], permissions: ["Spreadsheet creation", "Data analysis", "Chart generation", "File export"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
  { id: "design-sources", name: "Design Sources", description: "Collect approved UI references, compare component patterns, adapt them to Elias design tokens, preview the result, run visual QA, and prepare an implementation review without changing the repository until approval.", category: "official", status: "enabled", version: "1.0.0", updatedAt: "2026-08-26", tools: ["design.sources", "design.catalog", "design.preview", "design.visual-qa", "design.review-queue"], permissions: ["Public design-source retrieval", "Component cataloging", "UI adaptation", "Visual QA", "Repository review staging"], contributors: [{ name: "Elias Core", role: "Maintainer", kind: "official" }], evaluation: { cases: 0, passRate: 0 } },
];

export type ExtendedSkillId = typeof EXTENDED_SKILL_DEFINITIONS[number]["id"];

const TRIGGERS: Array<[ExtendedSkillId, RegExp]> = [
  ["elias-api", /Elias API|API v2|OAuth2|webhook|structured output|task lifecycle|connector API/i],
  ["typst-pdf-maker", /Typst|\.typ file|generate (a )?PDF|PDF report|compile a PDF|academic paper/i],
  ["video-generator", /generate (a )?video|video generator|short film|commercial|storyboard|video clip/i],
  ["youtube-video-research", /YouTube|video research|interview|keynote|conference talk|podcast|first-hand evidence/i],
  ["tts-prompter", /text[- ]to[- ]speech|TTS|voiceover|narration|spoken audio|voice prompt/i],
  ["stock-analysis", /stock|ticker|share price|10-K|10-Q|SEC filing|insider holdings|technical analysis|valuation/i],
  ["similarweb-analytics", /SimilarWeb|website traffic|traffic sources|bounce rate|visits|website ranking|geographic traffic/i],
  ["music-prompter", /generate music|song|soundtrack|beat|jingle|background music|instrumental|music prompt/i],
  ["excel-generator", /Excel|spreadsheet|workbook|xlsx|CSV analysis|pivot table|data bars/i],
  ["design-sources", /design sources|component catalog|UI library|UI libraries|Beautiful UI|beUI|Rare UI|shadcn|frontend design|design system|visual QA|adapt this component/i],
];

export function detectExtendedSkills(query: string, existing: string[] = []) {
  const detected = TRIGGERS.filter(([, pattern]) => pattern.test(query)).map(([id]) => id);
  return Array.from(new Set([...existing, ...detected]));
}

export function extendedSkillInstruction(id: ExtendedSkillId, query: string) {
  const common = "Use real data or clearly label unavailable adapters. Do not fabricate tool results. State assumptions and limitations. Ask for missing requirements when the skill requires them.";
  const instructions: Record<ExtendedSkillId, string> = {
    "elias-api": "Use API v2 patterns, scoped authentication, structured outputs, idempotency, webhooks for production delivery, and explicit confirmation for task actions or connector administration.",
    "typst-pdf-maker": "Create a content manifest, run deterministic planning and compile preflight, preserve one style owner, compile strictly, verify the PDF, and visually review representative pages. Route ordinary slide requests to slide generation instead.",
    "video-generator": "Gather purpose, audience, narrative, duration, 16:9 or 9:16 ratio, style, audio, and references first. Stop for confirmation before production. Require detailed clip transitions and reference images before video generation.",
    "youtube-video-research": "Discover multiple relevant videos, prefer first-hand sources, request direct quotes and all data points, analyze the videos, cross-validate claims, and cite each source. Never treat a speaker as unquestionable ground truth.",
    "tts-prompter": "Separate English director instructions from spoken text with a colon. Keep spoken text in its target language and use local markup tags only for sounds, pacing, or localized style shifts.",
    "stock-analysis": "Resolve the entity first, anchor the reference date and fiscal period, use primary or connected financial sources, distinguish market analysis from personal investment advice, and trace hardcoded numbers to sources.",
    "similarweb-analytics": "Normalize the domain, use monthly date-bounded data, respect the 12-month historical and 3-month country limits, save retrieved data immediately, and disclose the latest complete-month limitation.",
    "music-prompter": "Use a single prompt for tracks up to three minutes with duration first, then genre, tempo, key, mood, instrumentation, density, arrangement, soundscape, and production quality. Use multi-clip continuity only for longer tracks.",
    "excel-generator": "Understand the user’s decision need first, create a useful Overview sheet, use formulas and source attribution, format all numeric cells, add meaningful charts or validation, and use finance-specific formatting authority for finance models.",
    "design-sources": "Use approved public design libraries as references, inspect component documentation rather than blindly copying, check compatibility and licensing signals, map the selected pattern to Elias tokens, show a mobile and desktop preview, run responsive/contrast/focus QA, and stage the result for Agent review. Never modify or commit the repository without explicit user approval.",
  };
  return `[${id.toUpperCase()}]\nRequest: ${query}\n${common}\n${instructions[id]}`;
}
