import { PDFDocument } from "pdf-lib";
import { textToPdf } from "../lib/artifacts";

async function main() {
  const content = `# Verified ELIAS report\n\n## Findings\n\n- The provider must complete research before creating a PDF.\n- The artifact must contain final content.\n\n> This report was generated by the real PDF renderer.`;
  const encoded = await textToPdf(content);
  const bytes = Buffer.from(encoded, "base64");
  const document = await PDFDocument.load(bytes);
  if (document.getPageCount() < 1 || bytes.length < 500) throw new Error("PDF smoke test produced an empty document");
  console.log(JSON.stringify({ pages: document.getPageCount(), bytes: bytes.length, ok: true }));
}

void main();
